// Generated by CoffeeScript 2.4.1
(function() {
  "use strict";
  var CND, Multimix, alert, badge, debug, declare, echo, esc_re, help, info, isa, jr, log, rainbow, rpr, size_of, type_of, types, urge, validate, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'TUNNELTEXT/MAIN';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  rainbow = CND.rainbow.bind(CND);

  ({jr} = CND);

  Multimix = require('multimix');

  //...........................................................................................................
  types = require('./types');

  ({isa, validate, declare, size_of, type_of} = types);

  //-----------------------------------------------------------------------------------------------------------
  /* from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions */
  esc_re = function(text) {
    return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  };

  //===========================================================================================================
  this.Tunneltext = class Tunneltext extends Multimix {
    // @extend   object_with_class_properties
    // @include require './cataloguing'
    // @include require './sizing'
    // @include require './declaring'

    //---------------------------------------------------------------------------------------------------------
    constructor(chrs = null) {
      var chr_count, cloaked, delta, idx, master, meta_chr_patterns, target_seq_chrs, target_seq_patterns;
      super();
      if (chrs == null) {
        chrs = '\x10\x11\x12\x13\x14';
      }
      validate.tunneltext_chrs(chrs);
      chrs = Array.from(chrs);
      //.......................................................................................................
      chr_count = chrs.length;
      delta = (chr_count + 1) / 2 - 1;
      master = chrs[chr_count - delta - 1];
      meta_chr_patterns = (function() {
        var i, ref, results;
        results = [];
        for (idx = i = 0, ref = delta; (0 <= ref ? i <= ref : i >= ref); idx = 0 <= ref ? ++i : --i) {
          results.push(RegExp(`${esc_re(chrs[idx])}`, "g"));
        }
        return results;
      })();
      target_seq_chrs = (function() {
        var i, ref, results;
        results = [];
        for (idx = i = 0, ref = delta; (0 <= ref ? i <= ref : i >= ref); idx = 0 <= ref ? ++i : --i) {
          results.push(`${master}${chrs[idx + delta]}`);
        }
        return results;
      })();
      target_seq_patterns = (function() {
        var i, ref, results;
        results = [];
        for (idx = i = 0, ref = delta; (0 <= ref ? i <= ref : i >= ref); idx = 0 <= ref ? ++i : --i) {
          results.push(RegExp(`${esc_re(target_seq_chrs[idx])}`, "g"));
        }
        return results;
      })();
      cloaked = chrs.slice(0, delta);
      debug('µhd', 'delta:                ', rpr(delta));
      debug('µhd', 'master:               ', rpr(master));
      debug('µhd', 'meta_chr_patterns:    ', rpr(meta_chr_patterns));
      debug('µhd', 'target_seq_chrs:      ', rpr(target_seq_chrs));
      debug('µhd', 'target_seq_patterns:  ', rpr(target_seq_patterns));
      debug('µhd', 'cloaked:              ', rpr(cloaked));
    }

  };

  new this.Tunneltext('abcxy');

}).call(this);

//# sourceMappingURL=main.js.map
