// Generated by CoffeeScript 2.4.1
(function() {
  //###########################################################################################################
  var CND, FS, L, OS, PATH, alert, badge, debug, echo, help, info, log, rpr, test, urge, warn, whisper;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'TIMETUNNEL/TESTS/MAIN';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  PATH = require('path');

  FS = require('fs');

  OS = require('os');

  test = require('guy-test');

  //###########################################################################################################
  L = this;

  (async function() {
    await test(require('./basic.test'), {
      timeout: 5000
    });
    return (await test(require('./integer-codec.test'), {
      timeout: 5000
    }));
  })();

}).call(this);

//# sourceMappingURL=main.js.map
